### ISSUE TITLE
StyleRoot @Media Queries don't work properly if you are not using some kind of grid system - Chrome bug

### ISSUE THREAD

**Issue by interglobalmedia** [FormidableLabs/radium#944]
I first started using Radium and StyleRoot when I also was using CSS Grid for a project. Now I am using Radium and StyleRoot on another project in which I am not using any grid system. Only Flexbox. As a result, my Radium styles are not changing at the breakpoints I am specifying in my @media queries. They are changing at some other seemingly random breakpoints not of my choosing. Unless this was meant to me and I have overlooked something in the docs, I think this might be a **bug**.

Code:

```
import React, {Component} from 'react';
import Radium from 'radium';
import Slider from './components/Slider';
import Footer from './components/Footer';

import photoAug15100332 from '../images/photoAug15100332.jpg';
import photoAug15111608 from '../images/photoAug15111608.jpg';
import photoAug15111623 from '../images/photoAug15111623.jpg';
import photoAug15112130 from '../images/photoAug15112130.jpg';

const sliderData = [
	{
		src: photoAug15100332,
		credits: 'The Beauty'
	},
	{
		src: photoAug15111608,
		credits: 'The Plotter'
	},
	{
		src: photoAug15111623,
		credits: 'The Gazer'
	},
	{
		src: photoAug15112130,
		credits: 'The Ponderer'
	}
];

class App extends Component {
	render() {
		const headerStyle = {
			header: {
				height: '60px',
				textAlign: 'center',
				width: '100%'
			},
			h1: {
				width: '100%',
				zIndex: '10',
				top: '35px',
				position: 'absolute',
				color: '#b22222',
				left: '50%',
				transform: 'translateX(-50%)',
				fontSize: '1.5em',
				letterSpacing: '0.03em',
			},
			minWidth680H1: {
				'@media (min-width: 680px)': {
					fontSize: '2.5em',
					top: '20px'
				}
			},
			minWidth960H1: {
				'@media (min-width: 960px)': {
					fontSize: '2.5em',
					top: '20px'
				}
			}
		}
		return (
			<div className='App Site'>
				<header style={headerStyle.header}>
					<h1 style={[headerStyle.h1, headerStyle.minWidth680H1, headerStyle.minWidth960H1]}>Cat Slider</h1>
				</header>
				<div className='Site-content'>
					<Slider slides={sliderData} />
				</div>
				<Footer />
			</div>
		)
	}
}

export default Radium(App);
```
I also tried without the `all and` after @media first. Then I tried this way just in case. Same deal. The **breakpoint** I am getting right now that **changes the font size**  is **only one** and it's at **850px**. And the browser I have been using is Chrome. Then I went to double check if the same thing was happening in Firefox and Safari, and it was NOT. There it was FINE and worked like it should. I will check in **IE Edge** on my Windows Laptop when I have access to it tonight and let you know what transpires there. DEFINITELY a **browser-related BUG**. Thnx!

**Comment by interglobalmedia** [comment]
It seems that this is the issue: https://stackoverflow.com/questions/45025397/media-query-not-working-in-react The answer in the thread is that the last media query is chosen and that it is a css thing. I personally  have never come across this I don' t think in Chrome, especially with JS (non react) applications when using Chrome DevTools, but it is  a"thing" now with React in Chrome. As I mentioned earlier, it does not happen in Safari, Firefox, or Edge (tested). So it's an FYI. I removed Radium to see what would happen, and still have problems. The answer in Stack Overflow is not QUITE right, because my font does change twice, just not in the right place. Something is up with React, Chrome, and media queries. I'm using scss. Should this become a React issue? It's kind of a pretty deal in my opinion. Not being able to create a fully responsive web site that renders properly in Chrome is not good! This has never happened to me before.

**Comment by interglobalmedia** [comment]
Forget everything I said previously. I just pushed this project to Github, and the media queries work as expected. This is a bug that is specific to Chrome and occurs only locally for whatever reason. I will be writing about this too. It also seems to be specific to React. Don't know why this is seems to be occurring now. Perhaps also specific to 16+? Not quite sure, but will keep my eyes open to this. my work around will be to either use Firefox or Safari to render my React applications (and keep on checking with Chrome too for the hell of it) as that is how I will be able to gauge the responsiveness of my apps.

**Comment by ajGingrich** [comment]
did you ever figure out the problem for local chrome? I ran into the same issue today and it was driving me crazy but after reading your post I tried with firefox and the media queries worked as expected.

**Comment by antiproblemist** [comment]
I experienced the same issue with React + Next.js on Chrome. Bootstrap media queries work properly on Firefox and Safari but Chrome makes the app irresponsive. I want to know whether this issue persists in prodcution as well?

**Comment by tzuriely** [comment]
> I experienced the same issue with React + Next.js on Chrome. Bootstrap media queries work properly on Firefox and Safari but Chrome makes the app irresponsive. I want to know whether this issue persists in prodcution as well?

This you find any solution?

**Comment by ajGingrich** [comment]
> This you find any solution?

I personally quit using Radium and went with a different approach because of this issue.

**Comment by sprinkaan88** [comment]
For Chrome specifically, try adding this to your page's `<head>` section :
`<meta name="viewport" content="width=device-width,initial-scale=1">`

**Comment by evertonrbraga** [comment]
Besides the App component, you also have to wrap your App with the StyleRoot tag located in the index.js file.
Like this: <StyleRoot><App /></StyleRoot>
